### ISSUE TITLE
Please disable deepcode bot

### ISSUE THREAD

**Issue by isaacs** [shimi-eshkenazi/minimatch#1]
Hi, you have a bot that is spamming me.

https://github.com/shimi-eshkenazi/minimatch/commit/eed89491bd4a4e6bc463aac0dfb5c29ef0d1dc13#commitcomment-33086047

Anything you can do to turn that down a notch?  Thanks.

**Comment by shinin-light** [comment]
Sorry, that was a bug. It has been fixed.
